config/routes.rb
Rails.application.routes.draw do
  devise_for :users, prefix: 'worship_'

  resources :dashboard, only: [:index]
  resources :users
  resources :birthdays, only: [:index]
  resources :songs
  resources :hymns
  resources :events

  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index', as: 'authenticated'
    end

    unauthenticated :user do
      root to: 'devise/sessions#new', as: 'unauthenticated'
    end
  end

  root 'dashboard#index'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :songs, only: [:index, :show, :create, :update, :destroy]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # imports
  include DeviseInvitable::Inviter

  # relations
  has_many :songs, dependent: :destroy
  has_many :events, dependent: :destroy

  # filter methods
  after_initialize :set_default_role, if: :new_record?
  after_create :send_admin_mail

  # validations
  has_attached_file :image, styles: {
    small: "64x64",
    med: "100x100",
    large: "200x200"
  }, default_url: "med/missing.png"

  validates_attachment_content_type :image, content_type: [
    "image/jpg",
    "image/jpeg",
    "image/png",
    "image/gif"
  ]

  # enumerators
  enum role: [:user, :admin]

  # methods
  def set_default_role
    self.role ||= :user
  end

  def to_s
    [first_name, last_name].join(' ')
  end

  def send_admin_mail
    UserMailer.welcome_email(self).deliver_now
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :invitable,
         :database_authenticatable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  after_action :verify_authorized
  before_action :authenticate_user!

  def index
    @page_title = 'Usuários'
    @users = User.all
    authorize @users
  end

  def show
    @page_title = @user.first_name
    authorize @user
  end

  def new
    @page_title = 'Adicionar usuário'
    @user = User.new
    authorize User
  end

  def edit
    @page_title = @user.first_name
    authorize @user
  end

  def create
    @user = User.new(user_params)
    authorize @user
    if @user.save
      redirect_to @user, notice: 'O usuário foi criado com sucesso.'
    else
      render action: 'new'
    end
  end

  def update
    # avoid password validation while editing user
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    authorize @user

    if @user.update_attributes(user_params)
      redirect_to @user, notice: 'O usuário foi alterado com sucesso.'
    else
      render action: 'edit'
    end
  end

  def destroy
    authorize @user
    @user.destroy
    redirect_to users_url, notice: 'O usuário foi excluído com sucesso.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :birthday,
      :email,
      :password,
      :password_confirmation,
      :role,
      :image
    )
  end

end

app/helpers/user_helper.rb
module UserHelper
  def full_name(user)
    [user.first_name, user.last_name].join(' ')
  end

  def last_login(user)
    if user.last_sign_in_at.blank?
      return 'Never logged in'
    else
      return time_ago_in_words(@user.last_sign_in_at.to_datetime) + ' atrás'
    end
  end
end

app/views/users/_change_password.html.erb
<br/>
<h3>Redefinir Senha</h3>

<%= bootstrap_form_for(@user) do |f| %>

  <%= render partial: "shared/errors", locals: {record: @user }%>

  <div class="row">
    <div class="col-md-3">
      <%= f.password_field :password, label: 'Senha', class: 'form-control' %>
    </div>
    <div class="col-md-3">
      <%= f.password_field :password_confirmation, label: 'Confirmar Senha', class: 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit 'Redefinir', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= bootstrap_form_for(@user, html: { multipart: true }) do |f| %>

  <%= render partial: "shared/errors", locals: {record: @user }%>

  <div class="row">
    <div class="col-md-4">
      <%= f.file_field :image, label: 'Foto', class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <%= f.text_field :first_name, label: 'Nome', class: 'form-control' %>
    </div>
    <div class="col-md-4">
      <%= f.text_field :last_name, label: 'Sobrenome', class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class='form-inline'>
        <%= f.date_select :birthday, include_blank: true, default: nil, start_year: 1960, label: 'Aniversário', class: 'form-control form-group' %>
      </div>
    </div>
    <div class="col-md-4">
      <%= f.email_field :email, label: 'Email', class: 'form-control' %>
    </div>
  </div>

  <% if !current_page?("/users/#{@user.id}/edit") %>
    <div class="row">
      <div class="col-md-3">
        <%= f.password_field :password, label: 'Senha', class: 'form-control' %>
      </div>
      <div class="col-md-3">
        <%= f.password_field :password_confirmation, label: 'Confirmar Senha', class: 'form-control' %>
      </div>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit 'Salvar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= full_name user %></td>
  <td><%= user.email %></td>
  <td><%= role_description user.role %></td>

  <td>
    <%= link_to user, title: "Ver Detalhes", id: "show_user_#{user.id}" do %>
      <i class='glyphicon glyphicon-info-sign'></i>
    <% end %>
  </td>

  <td>
    <%= link_to edit_user_path(user), title: "Editar Usuário", id: "edit_user_#{user.id}" do %>
      <i class='glyphicon glyphicon-edit'></i>
    <% end %>
  </td>

</tr>

app/views/users/edit.html.erb
<h3>Editar usuário</h3>

<%= render 'form' %>

<%= render 'change_password' %>
<br/>
<%= link_to "Excluir conta", @user, method: :delete, data: { confirm: 'Você tem certeza?' }, class: "btn btn-danger" %>

app/views/users/index.html.erb
<h3>Usuários</h3>
<br/>
<div class="panel panel-primary">
  <div class="panel-heading">
    Relatório
  </div>
  <table id="users" class="table table-striped">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Função</th>
        <th colspan="4">Ações</th>
      </tr>
    </thead>
    <tbody>
      <%= render @users %>
    </tbody>
  </table>
</div>
<br/>
<%= link_to "Adicionar Usuário", new_user_path, class: 'btn btn-primary' %>
<%= link_to "Convidar Usuário", new_user_invitation_path, class: 'btn btn-primary' %>

app/views/users/new.html.erb
<h3>Novo Usuário</h3>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="well">
  <%= image_tag @user.image.url(:large) %>
  <h3>
    <%= full_name @user %>
  </h3>
</div>

<div class="well">

  <p>
    <b>Email:</b> <%= @user.email %>
  </p>

  <p>
    <b>Aniversário:</b> <%= date_format @user.birthday %>
  </p>

  <p>
    <b>Último Login:</b> <%= last_login @user %>
  </p>

  <p>
    <b>Criado em: </b><%= date_format @user.created_at %>
  </p>

  <p>
    <b>Atualizado em:</b> <%= date_format @user.updated_at %>
  </p>

  <p>
    <b>Número de logins: </b><%= @user.sign_in_count %>
  </p>
</div>