config/routes.rb
Rails.application.routes.draw do
  devise_for :users, prefix: 'worship_'

  resources :dashboard, only: [:index]
  resources :users
  resources :birthdays, only: [:index]
  resources :songs
  resources :hymns
  resources :events

  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index', as: 'authenticated'
    end

    unauthenticated :user do
      root to: 'devise/sessions#new', as: 'unauthenticated'
    end
  end

  root 'dashboard#index'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :songs, only: [:index, :show, :create, :update, :destroy]
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :title, presence: true
  belongs_to :user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @page_title = "Eventos"
    @events = Event.all
    authorize @events
  end

  def show
    @page_title = @event.title
    authorize @event
  end

  def new
    @page_title = "Adicionar evento"
    @event = Event.new
    authorize @event
  end

  def edit
    @page_title = @event.title
    authorize @event
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.try(:id)
    authorize @event
    if @event.save
      redirect_to @event, notice: 'O evento foi criado com sucesso.'
    else
      render :new
    end
  end

  def update
    authorize @event
    if @event.update(event_params)
      redirect_to @event, notice: 'O evento foi atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    authorize @event
    @event.destroy
    redirect_to events_url, notice: 'O evento foi excluído com sucesso.'
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(
      :title,
      :date,
      :start_time,
      :end_time,
      :address,
      :number,
      :complement,
      :zip_code,
      :neighborhood,
      :city,
      :observations,
      :user_id
    )
  end
end

app/helpers/event_helper.rb
module EventHelper
end

app/views/events/_event.html.erb
<tr>

  <td><%= event.title %></td>
  <td><%= date_format event.date %></td>
  <td><%= time_format event.start_time %></td>
  <td><%= time_format event.end_time %></td>

  <td>
    <%= link_to event, id: "show_event_#{event.id}", title: "Ver Detalhes" do %>
      <i class="glyphicon glyphicon-info-sign"></i>
    <% end %>
  </td>

  <td>
    <%= link_to edit_event_path(event), id: "edit_event_#{event.id}", title: "Editar Evento" do %>
      <i class="glyphicon glyphicon-edit"></i>
    <% end %>
  </td>

  <td>
    <%= link_to event, method: :delete, data: { confirm: 'Você tem certeza?' }, id: "delete_event_#{event.id}", title: "Excluir Evento" do %>
      <i class="glyphicon glyphicon-trash"></i>
    <% end %>
  </td>

</tr>

app/views/events/_form.html.erb
<%= bootstrap_form_for(@event) do |f| %>

  <%= render partial: "shared/errors", locals: {record: @event }%>

  <div class="row">
    <div class="col-md-4">
      <%= f.text_field :title, class: 'form-control', label: 'Título' %>
    </div>

    <div class="col-md-3">
      <%= f.date_field :date, class: 'form-control', label: 'Data'%>
    </div>

    <div class="form-inline time-fields col-md-4">
      <div class="form-group" style="margin-right: 20px">
        <%= f.time_select :start_time, class: 'form-control', label: 'Início'%>
      </div>
      <div class="form-group">
        <%= f.time_select :end_time, class: 'form-control', label: 'Término'%>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-9">
      <%= f.text_field :address, class: 'form-control', label: 'Endereço' %>
    </div>

    <div class="col-md-2">
      <%= f.text_field :number, class: 'form-control', label: 'Número' %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <%= f.text_field :complement, class: 'form-control', label: 'Complemento' %>
    </div>

    <div class="col-md-3">
      <%= f.text_field :zip_code, class: 'form-control', label: 'CEP' %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <%= f.text_field :neighborhood, class: 'form-control', label: 'Bairro' %>
    </div>

    <div class="col-md-4">
      <%= f.text_field :city, class: 'form-control', label: 'Cidade' %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-11">
      <%= f.text_area :observations, class: 'form-control', rows: 5, label: 'Observações' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit value: 'Salvar', class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/events/edit.html.erb
<h3>Editar Evento</h3>

<%= render 'form' %>

app/views/events/index.html.erb
<h3>Eventos</h3>
<br>
<div class="panel panel-primary">
  <div class="panel-heading">
    Relatório
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Título</th>
        <th>Data</th>
        <th>Horário de Início</th>
        <th>Horário de Término</th>
        <th colspan="4">Ações</th>
      </tr>
    </thead>

    <tbody>
      <% if @events.empty? %>
        <tr>
          <td colspan="4">Ainda não existem eventos registrados.</td>
        </tr>
      <% else %>
        <%= render @events %>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'Adicionar Evento', new_event_path, class: 'btn btn-primary' %>

app/views/events/new.html.erb
<h3>Novo Evento</h3>
<br/>
<%= render 'form' %>

app/views/events/show.html.erb
<div class="well">
  <h3><%= @event.title %></h3>
</div>

<div class="well">
  <p>
    <strong>Data:</strong>
    <%= date_format @event.date %>
  </p>

  <p>
    <strong>Horário de Início:</strong>
    <%= time_format @event.start_time %>
  </p>

  <p>
    <strong>Horário de Término:</strong>
    <%= time_format @event.end_time %>
  </p>

  <p>
    <strong>Endereço:</strong>
    <%= @event.address %>
  </p>

  <p>
    <strong>Número:</strong>
    <%= @event.number %>
  </p>

  <p>
    <strong>Complemento:</strong>
    <%= @event.complement %>
  </p>

  <p>
    <strong>CEP:</strong>
    <%= @event.zip_code %>
  </p>

  <p>
    <strong>Bairro:</strong>
    <%= @event.neighborhood %>
  </p>

  <p>
    <strong>Cidade:</strong>
    <%= @event.city %>
  </p>

  <p>
    <strong>Observações:</strong>
    <%= @event.observations %>
  </p>
</div>

<div>
  <p>
    <strong> Adicionado por </strong> <%= link_to @event.user, @event.user %> em </b><%= date_format @event.created_at %>
  </p>

  <p>
    <b>Última atualização:</b> <%= date_format @event.updated_at %>
  </p>
</div>