config/routes.rb
Rails.application.routes.draw do
  devise_for :users, prefix: 'worship_'

  resources :dashboard, only: [:index]
  resources :users
  resources :birthdays, only: [:index]
  resources :songs
  resources :hymns
  resources :events

  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index', as: 'authenticated'
    end

    unauthenticated :user do
      root to: 'devise/sessions#new', as: 'unauthenticated'
    end
  end

  root 'dashboard#index'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :songs, only: [:index, :show, :create, :update, :destroy]
    end
  end
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true

  before_create do
    self.week_number = Date.current.cweek if week_number.blank?
  end

  enum week_day: {
      'Domingo' =>       0,
      'Segunda-feira' => 1,
      'Terça-Feira' =>   2,
      'Quarta-Feira' =>  3,
      'Quinta-Feira' =>  4,
      'Sexta-Feira' =>   5,
      'Sábado' =>        6
  }

end

app/controllers/api/v1/songs_controller.rb
module Api
  module V1
    class SongsController < ApplicationController
      respond_to :json
      before_action :restrict_access

      def index
        respond_with(Song.all)
      end

      def show
        respond_with(Song.find(params[:id]))
      end

      def create
        @song = Song.new(song_params)
        if @song.save
          respond_to do |format|
            format.json { render json: @song }
          end
        end
      end

      def update
        @song = Song.find(params[:id])
        if @song.update(song_params)
          respond_to do |format|
            format.json { render json: @song }
          end
        end
      end

      def destroy
        respond_with Song.destroy(params[:id])
      end

      private

      def restrict_access
        api_key = ApiKey.find_by_access_token(params[:access_token])
        head :unauthorized unless api_key
      end

      def song_params
        params.require(:song).permit(:title,
          :singer, :lyrics, :chords, :week_number, :week_day, :user_id)
      end
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @page_title = "Louvores Avulsos"
    @songs = Song.where(week_number: Date.current.cweek)
    authorize @songs
  end

  def show
    @page_title = @song.title
    authorize @song
  end

  def new
    @page_title = "Adicionar louvor"
    @song = Song.new
    authorize @song
  end

  def edit
    @page_title = @song.title
    authorize @song
  end

  def create
    @song = Song.new(song_params)
    @song.user_id = current_user.try(:id)
    authorize @song
    if @song.save
      redirect_to @song, notice: 'O louvor foi adicionado com sucesso.'
    else
      render :new
    end
  end

  def update
    authorize @song
    if @song.update(song_params)
      redirect_to @song, notice: 'O louvor foi alterado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    authorize @song
    @song.destroy
    redirect_to songs_url, notice: 'O louvor foi excluído com sucesso.'
  end

  private

  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(
      :title,
      :singer,
      :lyrics,
      :chords,
      :week_number,
      :week_day,
      :user_id
    )
  end
end

app/helpers/song_helper.rb
module SongHelper
end

app/views/songs/_form.html.erb
<div class="songs-form">
  <%= form_for(@song) do |f| %>

    <%= render partial: "shared/errors", locals: {record: @song }%>

    <div class="row">
      <div class="form-group col-md-4">
        <%= f.label "Título" %><br>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group col-md-3">
        <%= f.label "Cantor/Banda"%><br>
        <%= f.text_field :singer, class: "form-control" %>
      </div>

      <div id="week_days" class="form-group col-md-2">
        <%= f.label "Dia da Semana" %><br>
        <%= f.select :week_day, options_for_select(Song.week_days.keys.to_a), {}, class: "form form-group form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-md-9">
        <%= f.label "Letra" %><br>
        <%= f.text_field :lyrics, class: "form-control", placeholder: "Copie e cole o link contendo a letra do louvor" %>
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-9">
        <%= f.label "Cifra" %><br>
        <%= f.text_field :chords, class: "form-control", placeholder: "Copie e cole o link contendo a cifra do louvor" %>
      </div>
    </div>

    <div class="actions">
      <br/>
      <%= f.submit "Salvar", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/songs/_song.html.erb
<tr>
  <td><%= song.title %></td>
  <td><%= song.singer %></td>
  <td><%= song.week_day %></td>

  <td>
    <%= link_to song, title: "Ver Detalhes", id: "show_song_#{song.id}" do %>
      <i class='glyphicon glyphicon-info-sign'></i>
    <% end %>
  </td>

  <td>
    <%= link_to edit_song_path(song), title: "Editar Louvor", id: "edit_song_#{song.id}" do %>
      <i class='glyphicon glyphicon-edit'></i>
    <% end %>
  </td>

  <td>
    <%= link_to song, method: :delete, data: { confirm: 'Você tem certeza?' }, title: "Excluir Louvor", id: "delete_song_#{song.id}" do %>
      <i class='glyphicon glyphicon-trash'></i>
    <% end %>
  </td>

</tr>

app/views/songs/edit.html.erb
<h3>Editar Louvor</h3>

<%= render 'form' %>

app/views/songs/index.html.erb
<h3>Louvores Avulsos</h3>
<br/>
<div class="panel panel-primary">
  <div class="panel-heading">
    Relatório
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Título</th>
        <th>Cantor/Banda</th>
        <th>Dia da Semana</th>
        <th colspan="4">Ações</th>
      </tr>
    </thead>

    <tbody>
      <% if @songs.empty? %>
        <tr>
          <td colspan="4">Ainda não existem louvores registrados.</td>
        </tr>
      <% else %>
        <%= render @songs %>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'Adicionar Louvor', new_song_path, class: "btn btn-primary" %>

app/views/songs/new.html.erb
<h3>Novo Louvor</h3>

<%= render 'form' %>

app/views/songs/show.html.erb
<div class="well">
  <h3><%= @song.title %></h3>
</div>

<div class="well">
  <p>
    <strong> Cantor/Banda: </strong> <%= @song.singer %>
  </p>

  <p>
    <strong> Letra: </strong> <%= extern_link @song.lyrics %>
  </p>

  <p>
    <strong> Cifra: </strong> <%= extern_link @song.chords %>
  </p>

  <p>
    <strong> Dia da Semana: </strong> <%= @song.week_day %>
  </p>

</div>

<div>
  <p>
    <strong> Adicionado por </strong> <%= link_to @song.user, @song.user %> em </b><%= date_format @song.created_at %>
  </p>

  <p>
    <b>Última atualização:</b> <%= date_format @song.updated_at %>
  </p>
</div>